name: CI Workflow

# "Explicit is better than implicit." — The Zen of Python
# Principle of Least Privilege / Explicit Permissions
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "List Files 1"
        run: ls -la

      # Most GitHub Actions workflows assume your repository’s code is already
      # present on the runner — but it isn’t. Runners start with an empty workspace,
      # and actions/checkout is the step that pulls your repo into $GITHUB_WORKSPACE
      # so the rest of your jobs can build, test, lint, or deploy.
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "List Files 2"
        run: ls -la

      - name: "Docker build"
        run: docker build -t arro:ci .
