name: Learn GitHub Actions

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: "List Files 1"
        run: ls -la

      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "List Files 2"
        run: ls -la
